name: test

on:
  repository_dispatch

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          echo '${{ toJson(github.event.client_payload.content) }}' > packages/packages.json

      - run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add packages/packages.json
          git commit -m "Update packages.json" || exit 0
          git push